### ISSUE TITLE
Use Pubmed ID If No DOI for Altmetric

### ISSUE THREAD

**Issue by sharpattack** [galterlibrary/primo-explore-devenv#27]
If there isn't a doi with a record, but a pubmed id is available, use this to get the altmetrics badge. See comment for more details. https://github.com/galterlibrary/primo-explore-devenv/pull/26#pullrequestreview-670587474

**Comment by jpastva** [comment]
Parking these articles here, which can be used for testing plugin behavior.

- PET Imaging of Brain Tumor with [methyl-11C]Choline (metadata only includes a PMID)

- Dostoevsky and Education through Punishment (metadata only includes a DOI)

**Comment by Meowcenary** [comment]
I'm looking into this and also [this ticket](https://github.com/galterlibrary/primo-explore-devenv/issues/30) which is sort of related.

Here are some useful links in the Primo documentation that I found:

- [Display PNX Record in Primo VE](https://knowledge.exlibrisgroup.com/Primo/Product_Documentation/020Primo_VE/Primo_VE_(English)/030Primo_VE_User_Interface/Display_PNX_Record_in_Primo_VE) - The PNX record seems to hold metadata for individual items in the Primo view
- [PNX Record Sections](https://knowledge.exlibrisgroup.com/Primo/Product_Documentation/Primo/Technical_Guide/010The_PNX_Record/010PNX_Record_Sections) - These are the different sections you can access within a PNX record. For example you might run something like `vm.parentCtrl.item.pnx.addata || '';` to get the addata section of a PNX record.
- [Additional Data Section](https://knowledge.exlibrisgroup.com/Primo/Product_Documentation/Primo/Technical_Guide/010The_PNX_Record/140The_Additional_Data_Section#ww1050167) - Seems like urls and ids for the record
- [Display Section](https://knowledge.exlibrisgroup.com/Primo/Product_Documentation/Primo/Technical_Guide/010The_PNX_Record/040The_Display_Section#ww1049849) - Data that is actually put into the record view and description

**Comment by jpastva** [comment]
@Meowcenary in case it helps, I tracked down the location of the Pubmed ID in the PNX record. Unlike the DOI, which is stored in vm.parentCtrl.item.pnx.addata.doi, the PMID is in vm.parentCtrl.item.pnx.display.identifier. I believe there are potentially other identifiers in there, so you would have to filter out the ones which contain PMID.

It took a bit of time for me to track this down, and the result was not what I would have expected, so hopefully that saves you a headache or two :)

**Comment by Meowcenary** [comment]
@jpastva , that was helpful! I noticed that the pmid is also under addata in the documentation. Unfortunately I'm not finding a pmid or doi for some of the records I'm looking at such as this one: https://search.library.northwestern.edu/discovery/jfulldisplay?docid=alma9980318086102441&context=L&vid=01NWU_INST:HSLV&lang=en&adaptor=Local%20Search%20Engine&tab=jsearch_slot&query=any,contains,cancer&offset=0

**Comment by jpastva** [comment]
@Meowcenary you are probably only likely to see DOIs and PMIDs in records that are coming from the Primo central index. We usually don't record these identifiers in local catalog records, which would include books and journal titles (you can see the source of the record as one of the last fields in the Details view). DOIs and PMIDs are primarily assigned to journal articles, book chapters, and other component parts of publications that would more likely be indexed by Primo. DOIs can be assigned to books and journals, but it isn't very common.

When you're testing in Primo, it is probably most helpful to look at articles, because that will only be results from the central index where these identifiers are likely to be present. Articles on humanities topics are less likely to have PMIDs because they wouldn't be indexed in Pubmed. And for DOIs, since it was introduced in 1997(?), anything published before that wouldn't be likely to have one.

**Comment by Meowcenary** [comment]
I'm still having some trouble with this. I've managed to get it working on my local instance, but when I deployed it to staging it was not working. Going to investigate this some more.

**Comment by Meowcenary** [comment]
Okay, it's working now. PR is going up.

**Comment by jpastva** [comment]
@Meowcenary I just noticed a record that displays the Altmetric badge twice - https://search.library.northwestern.edu/permalink/01NWU_INST/1a793gh/cdi_pubmedcentral_primary_oai_pubmedcentral_nih_gov_3222512

This may be due to the existence of both a DOI and PubMed ID in the metadata?
